app:
  env: ${HERMES_ENV:development}
  name: hermes
  description: Java Rest API- Communication Platform
  version: 0.0.1
  contact: Ramon Pereira
  url: https://www.linkedin.com/in/ramon-pereira-94a04b107/
  email: ramon.alves@live.com
spring:
  datasource:
    url: ${HERMES_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/hermes?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC}
    username: ${HERMES_DATASOURCE_USERNAME:albumstore}
    password: ${HERMES_DATASOURCE_PASSWORD:h3rm3s}
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    check-location: true
    enabled: true
    url: ${HERMES_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/hermes?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC}
    username: ${HERMES_DATASOURCE_USERNAME:albumstore}
    password: ${HERMES_DATASOURCE_PASSWORD:h3rm3s}